### ISSUE TITLE
Saw mill bug?? gives wrong item

### ISSUE THREAD

**Issue by DragonGirl7567** [MehVahdJukaar/sawmill#11]
recipes made with the sawmill are selecting different blocks

video to help explain it:

https://github.com/MehVahdJukaar/sawmill/assets/99091439/7645656b-1310-4d73-a619-aa5e7dabaa0b

(sorry of how fast it is, file size was to big)

sawmill-1.20-1.1.6.jar
moonlight-1.20-2.9.7-forge.jar
forge - 47.2.20

**Comment by MehVahdJukaar** [comment]
does this happen with latest version?

**Comment by MehVahdJukaar** [comment]
So try resetting your configs

**Comment by BalancedCracker** [comment]
Hi, I have same issue on my server and client.
I think, sawmill is working correctly in SSP game mode.
But, sawmill seems to have problems in SMP game mode.

sawmill-1.20-1.2.6.jar
moonlight-1.20-2.9.7-forge.jar
Minecraft 1.20.1 server and client with NeoForge-1.20.1-47.1.98
(and AutoRestart-1.20.1-2.0.2.jar in server)

I tried these:

1. erase config file of sawmill on server and client
2. shutdown and restart server and client
3. logged in server, and place sawmill
4. put 64 plunks on sawmill
5. I have some error messabes on server
<details><summary>Details</summary>
<p>

```
[10:34:43] [Server thread/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraftforge/client/event/ScreenEvent for invalid dist DEDICATED_SERVER
[10:34:43] [Server thread/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.RuntimeException: Attempted to load class net/minecraftforge/client/event/ScreenEvent for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-47.2.2.jar%2351!/:47.2] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar%2355!/:6.0.5+6.0.5+master.eb8e549b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar%2355!/:6.0.5+6.0.5+master.eb8e549b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar%2355!/:6.0.5+6.0.5+master.eb8e549b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
        at net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at net.mehvahdjukaar.sawmill.RecipeSorter.refreshIfNeeded(RecipeSorter.java:28) ~[sawmill-1.20-1.2.6.jar%23107!/:?] {re:classloading}
        at net.mehvahdjukaar.sawmill.RecipeSorter.sort(RecipeSorter.java:55) ~[sawmill-1.20-1.2.6.jar%23107!/:?] {re:classloading}
        at net.mehvahdjukaar.sawmill.SawmillMenu.setupRecipeList(SawmillMenu.java:158) ~[sawmill-1.20-1.2.6.jar%23107!/:?] {re:classloading}
        at net.mehvahdjukaar.sawmill.SawmillMenu.m_6199_(SawmillMenu.java:142) ~[sawmill-1.20-1.2.6.jar%23107!/:?] {re:classloading}
        at net.mehvahdjukaar.sawmill.SawmillMenu$1.m_6596_(SawmillMenu.java:50) ~[sawmill-1.20-1.2.6.jar%23107!/:?] {re:classloading}
        at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainer.java:144) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,re:mixin}
        at net.minecraft.world.inventory.Slot.m_269060_(Slot.java:59) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,re:mixin}
        at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,re:mixin}
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:410) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1550) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {}

``` 

</p>
</details> 

6. on client, everything looks like properly, including item sorting
7. picked product up from sawmill, and client has crashed
<details><summary>Details</summary>
<p>

```
[092月2024 10:34:58.183] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Container click
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:444) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23148!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23136!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.98.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 24
	at java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680) ~[?:?]
	at net.mehvahdjukaar.sawmill.SawmillMenu$2.m_142406_(SawmillMenu.java:68) ~[sawmill-1.20-1.2.6.jar%23154!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150418_(AbstractContainerMenu.java:418) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:416) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_171799_(MultiPlayerGameMode.java:431) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6597_(AbstractContainerScreen.java:536) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:329) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.mehvahdjukaar.sawmill.SawmillScreen.m_6375_(SawmillScreen.java:276) ~[sawmill-1.20-1.2.6.jar%23154!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	... 29 more
``` 

</p>
</details> 

8. restart client, and logged in again
9. put 64 plunks on sawmill again
10. select product on sawmill GUI, then sawmill shows wrong products
11. picked product up from sawmill, afterward i grumbled "no, that's not it"

**Comment by MehVahdJukaar** [comment]
You have a mod that is loading client side class from sever side one. It's their fault

**Comment by MehVahdJukaar** [comment]
Intact it might be forge itself. Update it!

**Comment by BalancedCracker** [comment]
Hmm, I'm not familiar with modding, so I don't understand what you mean.
In any case, I found that `sawmill-1.20-1.1.5.jar` worked as expected without causing an error on our server, so I decided to use it for a while.

Thank you so much for taking the time for me.
My friends are enjoying your mod, and so am I.

**Comment by Insane96** [comment]
I've been having a similar problem.
Mod 1.3.2 latest forge 1.20.1
Client side everything works properly, server side nope.
If you join a SP world and then join a server the items sort is wrong, making it craft the wrong item.
![image](https://github.com/MehVahdJukaar/sawmill/assets/7185104/bb57e242-47bb-4172-b870-76b30ae9dd2f)

**Comment by Insane96** [comment]
Forgot to mention that server side it works properly if you don't enter a SP world. The hammer is in the first place.

**Comment by MehVahdJukaar** [comment]
and are you all using at least forge 47.1.40  and NOT neoforge?

**Comment by Insane96** [comment]
Yep, latest forge 47.2.20

**Comment by MehVahdJukaar** [comment]
I cant replicate 💀 
I posted a possible fix, not sure if it will be helpful or not tho

**Comment by Insane96** [comment]
Try installing a mod that also adds a new wooden item

**Comment by Insane96** [comment]
I've tested the same problem with the latest fix, (1.3.3) and didn't work, I see you've released a .4 I will try that.
I've also noticed that only happens with the hammer from my mod ... so I might be doing something wrong?

**Comment by MehVahdJukaar** [comment]
Odd. Recipe order is generated by populating creative tans on server, then sending it over on days sync event (client shouldn't do any work here, even tho ideally creative tabs should always be the same from server to client)

**Comment by Insane96** [comment]
I'm quite sure Server doesn't know about creative tabs. I fill creative tabs in the ClientSetup phase

**Comment by MehVahdJukaar** [comment]
Creative tabs are not a client only class. While they do not get populated normally I call the populate method before accessing them. Newer version have the order entirely decided on server side. Anyways a "fix" would be to turn off recipe order via config. The desync happen when the server and client item order list don't match and idk how this could be the case since server populates it's own then send it over to clients on connection/reload

**Comment by Mxxstro** [comment]
Still having this issue, setting sort recipes to false doesn't do anything either. Past a certain point in the list, every item counts as the last "valid" crafting option. I'm on the latest versions of moonlight and forge as well.

**Comment by Insane96** [comment]
I no longer have that problem from the latest release even with sort_recipes set to true

**Comment by MehVahdJukaar** [comment]
Glad to hear at least it's not an issue for everybody. Here tho I really have no idea how to fix or what the issue even is. The recipe order list is now enforced to be exactly the same on server and clients and seeing this also happens with recipe sort of it's definitely not that. Apart from that both server and client just call recipevmanager.get recipe for container, same exact code. Only way that could fail if somehow server and client had different reipes but that's really impossible as vanilla enforces it and this desync would cause all sorts of other issues as well. After what item does that start to happen? What about the search box? Is that active?

**Comment by Mxxstro** [comment]
For me it starts bugging past the framed slab. The search bar works perfectly, but any item past the slab in the default list is still bugged even when deliberately searched.

**Comment by MehVahdJukaar** [comment]
Search bar Is client only but try turning it off anyways. Also try removing and trying without the fee mode close to the item at which this issue starts

**Comment by Mxxstro** [comment]
I'm not sure what that second part means, what am I supposed to do?

**Comment by MehVahdJukaar** [comment]
Try seeing if the issue persists without having installed the mods whose those items from which it starts to have a problem belong to

**Comment by MehVahdJukaar** [comment]
I will test with frames blocks

**Comment by Mxxstro** [comment]
How would I go about adding the mod ID to the blacklist? Every attempt so far has resulted in a crash when loading sawmill-common.toml

**Comment by MehVahdJukaar** [comment]
if it results in a crash means the confit is invalid, likely json syntax is too. log will say why

**Comment by Mxxstro** [comment]
Sorry, I meant to ask what's the proper syntax if I want to add framedblocks to the "mod_blacklist = []" line.

**Comment by MehVahdJukaar** [comment]
just add the mod id "framedblocks" within brackets

**Comment by dfederspiel** [comment]
https://github.com/MehVahdJukaar/sawmill/assets/251261/4888c5ee-0268-4b72-a13d-c08e3e0acff0

I have been experiencing a similar problem with a mod heavy installation. It seems to affect any item beyond 32 rows, at which point items chosen return the last item selected in rows 1-32. I can't reproduce in single player, but it's happening on multiplayer. `sort_recipes: false` in server config. I see bizarre behavior when it is set to true.

**Comment by MehVahdJukaar** [comment]
So you all curios to know whats actually going on? all my logic is fine as it turns out. Its the vanilla one that isnt. Minecraft sends over a packet on button click and as it turns out it doesnt care how many slots an inventory can have as the packet can hold at most 256 indexes as it uses a byte. not only that but as im not expecting it to be a byte its effectively half of that. checks out with your findings aswell

**Comment by MehVahdJukaar** [comment]
as a fix tbh i dont really see anybody having more than 256 recipes there at once. Framed blocks definitely has to be blacklisted as it has its own saw. I'll just adjust my code to expect a byte and cap showed recipes at 256

**Comment by Hyomoto** [comment]
Since these are all forge comments and because it's been a weird ride, I was using fabric 15.6 and sawmill 1.3.3 and getting some relief.  Had to redo the server due to a krypton bug and some mods were removed (shouldn't affect sawmill, but cest la vie I guess).  Anyways, hey, ordering bug shows up again.  I tried telling it to sort, and not to sort.  Delete configs.  Roll back versions.  I definitely have less than 256 items in the list, though I probably have more than 256 wooden items.

So yeah, setup here is with 15.7 fabric, sawmill 1.3.5 and I can't really spot the logic in the bug but it seems to be whatever list the item gets pulled from is sorted differently from the one I see as there is definitely a logic *to* it (the same item always picks the same different item) but it doesn't look like an "off by one" error.  Turning sorting on or off doesn't seem to affect the order at all so I'm wondering if there's something to that.

**Comment by MehVahdJukaar** [comment]
issue wasnt about lists differing. was abut vanilla not being able to send a button id further than 128 as integer. new version tahts now live allows up until 255 ids to work properly. Recipes shown are also capped at 255

**Comment by Hyomoto** [comment]
Updated to 1.3.7 and did a quick test, it *seems* to be working again.  I'm glad you were able to isolate it out, it was always a really weird bug especially since it seemed to get squashed at one point only to return.

**Comment by MehVahdJukaar** [comment]
well it was a totally different issue. Only happened when one had more than 128 recipe (which is very rare), due to how vanilla works.
