### ISSUE TITLE
[1.20.1] Sawmill changes something in the recipemanager that causes Mohist server to crash on startup

### ISSUE THREAD

**Issue by xhatz** [MehVahdJukaar/sawmill#30]
Hello! To reproduce, install the latest version of the mod on the latest version of a Mohist 1.20.1 hybrid server, it causes this error on loading:

`[14:09:52 INFO]: Initializing recipe event...
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/item/crafting/RecipeManager
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ReloadableServerResources.<init>(ReloadableServerResources.java:46)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ReloadableServerResources.m_247740_(ReloadableServerResources.java:75)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:38)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.lambda$main$2(Main.java:221)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:777)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:220)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.item.crafting.RecipeManager
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 23 more`

**Comment by MehVahdJukaar** [comment]
it says its caused by "java.lang.NoClassDefFoundError: net/minecraft/world/item/crafting/RecipeManager" which can never be the case unless one has a diferent veersion of the game. that is a minecraft class and ls always there on both server and client.
dont use mohist. Mods are meant to work with other mods. This is their issue if you really really want it to get fixed contact them not me. I would however strongly advise any kind of hybrid server. Just use mods,theres no need for plugins (which are literally serverside mods). Its literally having 2 competing loaders somehow "working" together in the same game. Nobody in the modding community recommends it and should not be needed too as proper forge mods can do all that plus way more

**Comment by xhatz** [comment]
I know it's not recommended, but for my use it's necessary, because there is no 1.20.1 mod that does precisely what I want (mainly multiple worlds instead of dimensions), but I can understand your POV.
