### ISSUE TITLE
[1.19.2] Lumberjack Villager Crash

### ISSUE THREAD

**Issue by Frogballoon** [MehVahdJukaar/sawmill#8]
Whenever I attempt to trade with the Lumberjack Villager, the game instantly crashes with exit code -1. Strangely enough, this was not happening before I leveled the villager up to the Journeyman level. I have no idea what in the world could be causing this. I am playing with 40+ other mods, which is quite a lot, so I'll make sure to leave a list so that you can Ctrl F for any known incompatibilities or something. I apologize for the lack of details and the crazy bug report that I brought you.  The mod loader is Fabric 0.15.0 and the version of Sawmill that I am using is 1.1.1.
- Architectury
- bclib
- Bedrockify
- Biome Makeover
- Bookshelf
- Cloth Config
- Collective
- Consistency
- Create
- Create: Steam N' Rails
- EasyMagic
- Enchancement
- Enchantment Descriptions
- Enderscape
- Eureka!
- Fabric API
- Kotlin
- Ferrite Core
- Galosphere
- Geckolib
- Good Ending
- Iceberg
- jamlib
- Kambrik
- Kiwi
- Midnightlib
- Moonlight
- Naturalist
- Nature's Compass
- Pehkui
- Polymer
- PuzzlesLib
- ResourcefulConfig
- Sawmill (obviously)
- Satin
- Sleep Tight
- Species
- Unvoted and Shelved
- Valkyrien Skies
- Villager Names
- You've Goat to Be Kidding Me!

**Comment by MehVahdJukaar** [comment]
i need latest.log

**Comment by Frogballoon** [comment]
I apologize :(
Here it is

[20:33:45] [Render thread/INFO]: Loading config file: C:\Users\frog\curseforge\minecraft\Instances\frogpack\config\jei\jei-mod-id-format.ini
[20:34:16] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
	at java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:564) ~[?:?]
	at java.util.List.of(List.java:829) ~[?:?]
	at net.mehvahdjukaar.sawmill.CarpenterTrades.lambda$static$0(CarpenterTrades.java:150) ~[sawmill-1.19-1.1.1-fabric.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[valkyrienskies-119-2.1.2-beta.1.jar:?]
	at net.mehvahdjukaar.sawmill.CarpenterTrades.getTypeSpecificWoodType(CarpenterTrades.java:183) ~[sawmill-1.19-1.1.1-fabric.jar:?]
	at net.mehvahdjukaar.sawmill.CarpenterTrades$WoodToItemListing.method_7246(CarpenterTrades.java:115) ~[sawmill-1.19-1.1.1-fabric.jar:?]
	at net.minecraft.class_3988.method_19170(class_3988.java:251) ~[client-intermediary.jar:?]
	at net.minecraft.class_1646.method_7237(class_1646.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_1646.method_16918(class_1646.java:759) ~[client-intermediary.jar:?]
	at net.minecraft.class_1646.method_5958(class_1646.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6023(class_1308.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2641) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:553) ~[client-intermediary.jar:?]
	at net.minecraft.class_1296.method_6007(class_1296.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.class_1646.method_5773(class_1646.java:318) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:712) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:371) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[client-intermediary.jar:?]
	... 5 more
[20:34:16] [Server thread/ERROR]: This crash report has been saved to: C:\Users\frog\curseforge\minecraft\Instances\frogpack\crash-reports\crash-2024-01-29_20.34.16-server.txt
[20:34:16] [Server thread/INFO]: [STDOUT]: Saving server results
[20:34:16] [Server thread/INFO]: Stopping server
[20:34:16] [Server thread/INFO]: Saving players
[20:34:16] [Physics thread/INFO]: [STDOUT]: Running deletePhysicsResources
[20:34:16] [Physics thread/INFO]: Deleting VSPhysicsPipelineStage resources!
[20:34:16] [Physics thread/WARN]: Physics pipeline ending

**Comment by MehVahdJukaar** [comment]
check if it still happens with latest version
